### ISSUE TITLE
Missing `coiled` command in conda-based installation on Windows

### ISSUE THREAD

**Issue by jgawad** [coiled/feedback#95] opened 2021-01-01 11:13 UTC
It seems coiled-0.0.32 conda package for Windows does not install proper `coiled.exe` CLI launcher.

The installation procedure I followed was:
```cmd
conda create -n coiled-x -c defaults -c conda-forge python=3.8 coiled
```

The conda package installs something that looks like coiled-script as 
`<environment path>\Scripts\coiled`. The file has no extension (neither .py nor .pyw).

---

Quick workaround for those who also encounter this issue:
Pip wheel installs the launcher `coiled.exe`, so a quick fix to get a workable conda environment with coiled is:
```cmd
pip uninstall coiled
pip install -U coiled
```
Note that we need to uninstall coiled first, but using `pip`, not `conda remove`.

**Comment by FabioRosado** [comment] 2021-01-04 23:02
Hello and thank you for reporting this issue and providing a workaround, that will help a lot. I'm assuming that you have your environment working as expected after uninstalling coiled with pip. I'll try to fix this issue so the `coiled` command works as expected.

**Comment by FabioRosado** [comment] 2021-01-07 16:02
I know it has been a while since I gave you an update. I have reproduced the issue on my windows machine, tested our recipe locally and it was able to create the executable. I've reached out to the conda-forge folks to see if they can help me debug this issue.

Again thank you for reporting this to us 😄

**Comment by FabioRosado** [comment] 2021-01-15 23:39
Hello @jgawad  We have released a new version of coiled, I've tested the same command that you reported this issue with, and I can now use the `coiled` command as expected on windows.

I will close this issue now since the new version fixes this bug, but please feel free to raise any more issues or ask us a question on slack if you encounter any other issues.

Let me also thank you again for reporting this to us 😄 👍

**Closed by FabioRosado** 2021-01-15 23:39 UTC
