### ISSUE TITLE
Cluster appears twice in cluster list

### ISSUE THREAD

**Issue by selshowk** [coiled/feedback#47] opened 2020-08-15 14:04 UTC
I tried starting a cluster with the same name as a previously stopped cluster and the client was not doing anything but restarting my python process and refreshing the cluster screen in the UI I see multiple instances of the previously stopped cluster in the cluster list (see screenshot):

![image](https://user-images.githubusercontent.com/67599884/90313997-c96c2500-df10-11ea-84f4-e3c5cc9c6dce.png)

This might be an ajax issue as it gets fixed when I reload the page.

**Comment by dantheman39** [comment] 2020-09-04 19:52
I'm late to the party here, sorry, but it is entirely possible that there be two clusters with the same name in the table, since they're uniquely identified by ID (you can start another cluster with the same name as another one, if the previous one is stopped). Your reaction Sheer that this is a mistake is totally understandable, I wonder what we should do to make this clearer.

My guess about it going away is that we had a bug where clusters that stopped shortly after starting up weren't being shown in the table, but that was recently fixed (so now it's _more_ likely that you'll see duplicates!).

Could you let us know if there is still some bad behavior around this?

**Comment by FabioRosado** [comment] 2021-02-05 00:26
I've tried to reproduce this issue but wasn't able to see any weird behaviour. Since I'm doing some clean up on the repo, I'm going to close this issue, but if you see this behaviour again feel free to re-open it 👍

**Closed by FabioRosado** 2021-02-05 00:26 UTC
