### ISSUE TITLE
Last Seen value keeps changing on stopped cluster

### ISSUE THREAD

**Issue by sterlinm** [coiled/feedback#55] opened 2020-08-27 21:24 UTC
The timestamp for "Last Seen" on the [Clusters](https://beta.coiled.io/clusters) tab keeps changing every second even though the status of the cluster is "Stopped". I may be misunderstanding the meaning of Last Seen but it gives me the impression the cluster is still running.

**Comment by mrocklin** [comment] 2020-08-28 01:16
Hi @sterlinm !  

Thank you for the issue.  Indeed that does sound problematic :) 

cc'ing @dantheman39 to make him aware.

**Comment by dantheman39** [comment] 2020-09-04 19:45
Just pointing out that I haven't seen this happen yet, if it's still an issue then hopefully you may have some steps to reproduce?

My guess is that indeed the cluster _was_ still running since that value is updated by the heartbeat code, so somehow the status was set to stopped when it wasn't quite stopped.

Either way thanks for the issue, if it's not a fluke we can look into it!

**Comment by sterlinm** [comment] 2020-09-06 19:11
I noticed it happened when I just ran threw the simple intro to using coiled and then shut down the cluster, but I will see if I can reproduce. It could have been a fluke or my misunderstanding of the dashboard.

**Comment by FabioRosado** [comment] 2021-02-04 23:46
Hello, I am going through the open issues and closing some of them. I've spun up a cluster and stopped it when the cluster is stopping the countdown keeps going, but once it stops, the times stay the same. 

I'll close this issue, but please feel free to re-open or create a new one if you think the issue still persists 😄

**Closed by FabioRosado** 2021-02-04 23:46 UTC
